git:
  depth: false
  quiet: true
  submodules: false

services:
  - docker

script:
  - "VERSION=$TRAVIS_BUILD_NUMBER make image"

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
    VERSION=$TRAVIS_BUILD_NUMBER make push-image ;
    fi
