git:
  depth: false
  quiet: true
  submodules: false

branches:
  only:
    - master

services:
  - docker

script:
  - "VERSION=$TRAVIS_BUILD_NUMBER make image"

after_success:
  docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
  VERSION=$TRAVIS_BUILD_NUMBER make push-image ;
