env:
  - VERSION="0.$TRAVIS_BUILD_NUMBER"

git:
  depth: false
  quiet: true
  submodules: false

branches:
  only:
    - master

services:
  - docker

script:
  - "VERSION=$VERSION make image"

after_success:
  docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
  VERSION=$VERSION make push-image ;
